### ISSUE TITLE
Feature Request: Include interface index

### ISSUE THREAD

**Issue by NfNitLoop** [bnoordhuis/netif#3]
Some socket APIs require an "interface index" to disambiguate addresses that might be applicable to multiple interfaces.

Examples:
 * [join_multicast_v6(addr, interface)][1] (+ [leave][2])
 * [set_multicast_if_v6(interface)][3]
 
[1]: https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.join_multicast_v6
[2]: https://doc.rust-lang.org/std/net/struct.UdpSocket.html#method.leave_multicast_v6
[3]: https://docs.rs/socket2/0.4.4/socket2/struct.Socket.html#method.set_multicast_if_v6

For link-local addresses, this seems to be equivalent to their `scope_id`. (Though I haven't found that explicitly documented anywhere. 😅).

However global or unique-local addresses don't require a scope ID, so they have a scope ID of `Some(0)`. But for the above APIs, an interface index of 0 means "unspecified", and can result in the [wrong behavior][4].

[4]: https://twitter.com/NfNitLoop/status/1495476322688278532

So, it would be nice if `netif` would also expose the "interface ID" with each of the `Interface`s it returns.

Additionally, it might be nice to provide an interface that either iterates physical interfaces, or groups the returned addresses by physical interfaces.

---

Thanks for this library! It seems to be working well for me in Windows and macOS so far. 👍

**Comment by bnoordhuis** [comment]
I'm not completely clear on what the ask is.

netif's `scope_id` is the `sin6_scope_id` (which is indeed what you want to use for the libstd functions you link to) but it sounds like you want to see `None` unless the interface address is link-local? That should already be possible:
```rust
for ifa in netif::up() {
    let scope_id = match ifa.address() {
        IpAddr::V6(addr) if addr.is_unicast_link_local() => ifa.scope_id(),
        _ => None,
    };
    // ...
}
```

> it might be nice to provide an interface that either iterates physical interfaces, or groups the returned addresses by physical interfaces.

Not 100% sure what you mean. Can you give an example of what that would look like?

**Comment by NfNitLoop** [comment]
> but it sounds like you want to see None unless the interface address is link-local

No. My request is to have the interface index available even for non-local addresses.

As a concrete example, say I have a Unique Local Address like this:

`fd49::beef`.  And I want to listen on the multicast address `ff02::1`.  

netif gives me:

```
Interface {
    name: "Ethernet",
    flags: 0,
    mac: [...],
    address: fd49::beef,
    scope_id: Some(
        0,
    ),
    netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff,
}
```

So I can't get from that what interface index I should provide if I want to listen on that address('s physical/virtual network interface).

> Not 100% sure what you mean. Can you give an example of what that would look like?

So here's how I've worked around it locally.  I iterate through all netif `Interface`s and group them by name.
Then, I can check if any of them have a non-zero scope ID, and use that as the "interface index" for all addresses on that network.

```rust
// A physical/virtual network interface. (vs netif's `Interface`, which is more like a network address.)
struct Physical {
    interfaces: Vec<Interface>,

    /// AKA "interface index":
    /// With current netif API, will only be known if there are link-local ipv6 addresses on this physical interface.
    interface_id: Option<u32>,

    mac: [u8; 6],
    name: String,
}

fn physical_interfaces() -> Result<Vec<Physical>, Error> {
    let interfaces: Vec<_> = netif::up()?.collect();

    // Group by physical interface.
    // MAC addresses might not be unique, since virtual interfaces often have all 0s.
    // Hopefully interface names are unique, but we'll verify:
    let mut map = HashMap::new();
    for interface in interfaces {
        let name = interface.name().to_string();
        let entry = map.entry(name).or_insert_with(|| vec![]);
        entry.push(interface);
    }

    let mut phys = vec![];
    
    for (name, interfaces) in map.into_iter() {
        let mut interface_id = None;
        let mut mac = None;
        for interface in &interfaces {
            if let Some(id) = interface.scope_id() {
                if id == 0 {
                    // This is a placeholder, meaning no scope/interface ID.
                } else if let Some(previous_id) = interface_id {
                    if id != previous_id {
                        bail!("Got conflicting scope/interface IDs for {name}: {previous_id} vs. {id}");
                    }
                } else {
                    interface_id = Some(id);
                }
            }
            if let Some(previous_mac) = mac {
                let new_mac = interface.mac();
                if new_mac != previous_mac {
                    bail!("Got conflicting MAC addresses for network {name}: {previous_mac:?} vs {new_mac:?}")
                }
            } else {
                mac = Some(interface.mac());
            }
        }
        phys.push(Physical{
            name: name,
            mac: mac.expect("Some MAC address"),
            interface_id,
            interfaces
        })
    }

    Ok(phys)
}

```

**Comment by bnoordhuis** [comment]
> say I have a Unique Local Address like this: fd49::beef. And I want to listen on the multicast address ff02::1. netif gives me: [..]

I think I understand what you mean now but I'm still not sure what you'd expect to see instead. Where would netif get that other interface index from?

**Comment by NfNitLoop** [comment]
> Where would netif get that other interface index from?

That, I don't know. I haven't delved much lower into networking code before. (Except for #4, which was interesting to learn about.)

I'd hope that (since interface index is sometimes needed in these cases where you're not using a link-local IPv6 address) the underlying OS APIs would provide some way to get that interface index.  But maybe that's not the case? 😅 

--- 

Worst case, you could do the brute force approach that I do above.  If you don't want to do it for all cases, you could expose a new API call that does this work for those that would like it.  (Me! 🖐️ 😊). That would also be a good opportunity to add this data structure that groups by (physical/virtual) network interface.

I'd be happy to clean up the above code and make a PR with a proposed API addition if you'd like to go that route.  (I'd probably rename `Physical` to something like `NetworkInterface` and create proper error types.)

**Comment by bnoordhuis** [comment]
> [..] the underlying OS APIs would provide some way to get that interface index. But maybe that's not the case?

Not that I'm aware of (or maybe I still misunderstand.)

The collation/grouping you do in your other comment doesn't really belong in netif, IMO, that's a higher-level concern.
