### ISSUE TITLE
Changes in memory layout of the std net types will result in UB

### ISSUE THREAD

**Issue by ghost** [bnoordhuis/netif#9]
Context: https://github.com/rust-lang/rust/pull/78802 and https://www.reddit.com/r/rust/comments/wcw93o/a_major_refactor_of_rusts_ip_address/

These lines caught my eye while I was reading the code:

https://github.com/bnoordhuis/netif/blob/550ec42328bbf680328fbaefa9bbeecb36f3e403/src/lib.rs#L189-L190

https://github.com/bnoordhuis/netif/blob/550ec42328bbf680328fbaefa9bbeecb36f3e403/src/lib.rs#L331-L332

A lot of crates were recently patched to remove the assumption of the memory layout of network primitives. Any code continuing to do so will result in UB, so I wanted to raise this issue.

**Comment by bnoordhuis** [comment]
It should be fairly easy to fix. Do you want to send a PR or should I?

**Comment by ghost** [comment]
I never used libc/winapi or unsafe stuff, so I probably wouldn't know what to do. I'll leave it to you =)
